"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class motor_response_t(object):
    __slots__ = ["id", "p", "v", "i"]

    __typenames__ = ["double", "double", "double", "double"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.id = 0.0
        self.p = 0.0
        self.v = 0.0
        self.i = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(motor_response_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dddd", self.id, self.p, self.v, self.i))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_response_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_response_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motor_response_t()
        self.id, self.p, self.v, self.i = struct.unpack(">dddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if motor_response_t in parents: return 0
        tmphash = (0xe476554587415a1c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motor_response_t._packed_fingerprint is None:
            motor_response_t._packed_fingerprint = struct.pack(">Q", motor_response_t._get_hash_recursive([]))
        return motor_response_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

